### ISSUE TITLE
New release (v1.4)

### ISSUE THREAD

**Issue by soullivaneuh** [hipchat/hipchat-php#25]
Can you guys push a new stable release for #23 implement?

As a new feature,`v1.4` should be the best.

This is needed for another library dependent of yours with this new feature: https://github.com/ManneW/HipChatBundle/pull/6

ping @zsiddique @powdahound

Regards

**Comment by ManneW** [comment]
:+1: 

Just wanted to add that this also would be beneficial for other packages dependent on hipchat/hipchat-php (that want to leverage this new feature) too :-)

**Comment by ManneW** [comment]
I don't want to bug you too much, but would it be possible for you to tag a new release? :-)

The only modification made since the currently latest release (1.3) would be the addition of the set_timeout feature in #23. This addition is also fully backwards compatible and respects the current defaults (if you don't change your configuration, there is no change in behavior).

Thanks in advance!

**Comment by zsiddique** [comment]
Went ahead and created a v1.4 tag and its released to packagist.org.  Sorry for the delay just feel off my radar.
